### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by bquorning**
How about a green build?

Well, the `there_and_back_again_test.rb` fails from time to time, so it would be nice if someone could stabilize it.

### CODE REVIEW

**Comment by bquorning** [comment]
@osheroff @pschambacher

**Comment by pschambacher** [comment]
:+1:

**Comment by pschambacher** [comment]
Merge?

**Comment by bquorning** [comment]
We’re ok with dropping support for Rails 2.3 and 3.0?

**Comment by pschambacher** [comment]
You might want a final confirmation from Ben but I really don't see why we should bother with Rails versions so old.

**Comment by bquorning** [comment]
Let’s move forward and revert if needed. This PR is 3 weeks old.

**Comment by osheroff** [comment]
:+1: I'm back from vacation.  should really move this repo to the zendesk org.

**Pull request merged**
