### PR TITLE
Test compatibility with Rails 5.0

### PR DESCRIPTION
**Pull request by bquorning**
~~Blocked by #20.~~

### CODE REVIEW

**Comment by bquorning** [comment]
Please try re-running the failing spec – I think it’ll eventually pass.

**Comment by bquorning** [comment]
cc @osheroff @pschambacher

**Comment by pschambacher** [comment]
:+1:

**Comment by bquorning** [comment]
@osheroff Not super urgent (since there are no code changes), but I think this PR is ready to merge.

**Comment by osheroff** [comment]
k.

**Pull request merged**
